---
apiVersion: v1
kind: Namespace
metadata:
  name: flowise
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flowise
  namespace: flux-system
spec:
  interval: 24h
  url: https://cowboysysop.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flowise
  namespace: flowise
spec:
  interval: 30m
  chart:
    spec:
      chart: flowise
      version: 3.11.1
      sourceRef:
        kind: HelmRepository
        name: flowise
        namespace: flux-system
      interval: 12h

  values:
    persistence:
      enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: le-prod
      hosts:
         - host: ${flowiseIngressHost:flowise.k8s.vincentdupain.com}
           paths:
             - /
      tls:
        - secretName: flowise-tls
          hosts:
            - ${flowiseIngressHost:flowise.k8s.vincentdupain.com}

