---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-infra
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: metallb-cilium
  url: https://github.com/vdupain/gitops-k8s-infra.git
