apiVersion: v1
kind: ConfigMap
metadata:
  name: apps-vars
  namespace: flux-system
data:
  podinfoIngressHost: "podinfo.homelab.vincentdupain.com"
  # opensearchIngressHost: "logging.homelab.vincentdupain.com"
  # openwebuiIngressHost: "open-webui.homelab.vincentdupain.com"
  ollamaIngressHost: "ollama.homelab.vincentdupain.com"
  flowiseIngressHost: "flowise.homelab.vincentdupain.com"
  n8nIngressHost: "n8n.homelab.vincentdupain.com"
