apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-vars
  namespace: flux-system
data:
  ciliumLoadBalancerIPPoolBlockStart: "192.168.10.210"
  ciliumLoadBalancerIPPoolBlockStop: "192.168.10.215"
  corednsServiceAnnotationCiliumLBIPAddrMgmt: "192.168.10.210"
  traefikServiceAnnotationCiliumLBIPAddrMgmt: "192.168.10.211"
  externalDnsDomainFilter: "homelab.vincentdupain.com"
