apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: le-prod
      hosts:
        - host: podinfo.k8s.vincentdupain.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: podinfo-service-cert
          hosts:
            - podinfo.k8s.vincentdupain.com