apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: podinfo.k8s.vincentdupain.com
          paths:
            - path: /
              pathType: ImplementationSpecific
