apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ollama.service.yaml
- ollama.statefulset.yaml
- open-webui.namespace.yaml
- webui.deployment.yaml
- webui.ingress.yaml
- webui.pvc.yaml
- webui.service.yaml
