---
apiVersion: v1
kind: Namespace
metadata:
  name: ollama
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ollama
  namespace: flux-system
spec:
  interval: 24h
  url: https://otwld.github.io/ollama-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
spec:
  interval: 30m
  chart:
    spec:
      chart: ollama
      version: 0.64.0
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: flux-system
      interval: 12h

  values:
    ollama:
      gpu:
        enabled: true
        type: 'nvidia'
        number: 1
      # -- List of models to pull at container startup
      models: 
        - llama2
    ingress:
      enabled: false
      hosts:
      - host: ollama.k8s
        paths:
          - path: /
            pathType: Prefix

