---
apiVersion: v1
kind: Namespace
metadata:
  name: open-webui
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.openwebui.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 30m
  chart:
    spec:
      chart: open-webui
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
      interval: 12h

  values:
    service:
      nodePort: 30000
    ollama:
      enabled: true
      gpu:
        enabled: true
        type: 'nvidia'
        number: 1
      # -- List of models to pull at container startup
      models:
        - mistral
        - llama3
      persistentVolume:
        enabled: true



