---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-apps
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: poc
  url: https://github.com/vdupain/gitops-k8s-apps.git
