apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-infra-configs
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-infra
  dependsOn:
  - name: k8s-infra-network
  - name: k8s-infra-security

