apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco
resources:
  - falco.yaml
  - falco.values.configmap.yaml
  - custom-rules.configmap.yaml
  - fluent.yaml
  - fluent.values.configmap.yaml
  - vector-falcosidekick.helmrelease.yaml
