---
apiVersion: v1
kind: Namespace
metadata:
  name: zfs-system
  labels:
    vector.dev/exclude: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: zfs-localpv
  namespace: flux-system
spec:
  interval: 24h
  url: https://openebs.github.io/zfs-localpv
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zfs-localpv
  namespace: zfs-system
spec:
  interval: 30m
  chart:
    spec:
      chart: zfs-localpv
      version: 2.7.0-develop
      sourceRef:
        kind: HelmRepository
        name: zfs-system
        namespace: flux-system
      interval: 12h
  releaseName: zfs-localpv

  values:
    zfsNode:
      encrKeysDir: /var/zfsencrkeys
