---
apiVersion: v1
kind: Namespace
metadata:
  name: airbyte
  labels:
    vector.dev/exclude: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: airbyte
  namespace: flux-system
spec:
  interval: 15m
  url: https://airbytehq.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airbyte
  namespace: airbyte
spec:
  chart:
    spec:
      chart: airbyte
      version: 1.2.0-rc-0f9cffefa08
      sourceRef:
        kind: HelmRepository
        name: airbyte
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: airbyte
  
  valuesFrom:
  - kind: ConfigMap
    name: airbyte-values
    valuesKey: values.yaml