---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-iac
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/vdupain/gitops-iac
  ref:
    branch: main
