apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- logging.namespace.yaml
- opensearch-dashboards.helmrelease.yaml
- opensearch.helmrelease.yaml
- opensearch.helmrepo.yaml
- post-config.configmap.yaml
- post-config.job.yaml
- vector.helmrelease.yaml
- vector.helmrepo.yaml
