apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opensearch
  namespace: logging
spec:
  interval: 30m
  chart:
    spec:
      chart: opensearch
      version: 1.6.2
      sourceRef:
        kind: HelmRepository
        name: opensearch
        namespace: flux-system
      interval: 12h
  releaseName: opensearch

  values:
    coordinating:
      replicaCount: 0
    data:
      replicaCount: 0
    ingest:
      replicaCount: 0
    master:
      replicaCount: 3
      masterOnly: false
      persistence:
        size: 2Gi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          jobLabel: opensearch
    dashboards:
      enabled: true
      ingress:
        enabled: true
        hostname: ${opensearchIngressHost}
        annotations:
          cert-manager.io/cluster-issuer: le-prod
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "OpenSearch"
          gethomepage.dev/group: "Observability"
          gethomepage.dev/pod-selector: "app.kubernetes.io/name=opensearch"
        ingressClassName: traefik
        tls: true
