apiVersion: batch/v1
kind: Job
metadata:
  name: opensearch-post-config-job
  namespace: logging
spec:
  template:
    metadata:
      labels:
        app: opensearch-post-config-job
    spec:
      volumes:
      - name: opensearch-post-config-job-volume
        configMap:
          name: opensearch-post-config-script
          defaultMode: 0777
      containers:
        - name: opensearch-post-config-job
          image: yauritux/busybox-curl
          volumeMounts:
            - name: opensearch-post-config-job-volume
              mountPath: /scripts
          env:
            - name: OPENSEARCH_SERVER
              value: http://opensearch.logging:9200
            - name: OPENSEARCH_USER
              value: admin
            - name: OPENSEARCH_PASSWORD
              value: admin
          command:
            - /scripts/opensearch-post-config-job.sh
      restartPolicy: OnFailure
