---
apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-device-plugin
  labels:
    # https://www.talos.dev/v1.7/kubernetes-guides/configuration/pod-security/
    pod-security.kubernetes.io/enforce: privileged
    vector.dev/exclude: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvdp
  namespace: flux-system
spec:
  interval: 15m
  url: https://nvidia.github.io/k8s-device-plugin
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-device-plugin
spec:
  chart:
    spec:
      chart: nvidia-device-plugin
      sourceRef:
        kind: HelmRepository
        name: nvdp
        namespace: flux-system
      version: 0.16.2
  interval: 15m
  timeout: 5m

  values:
    gfd:
      enabled: true
    config:
      map:
        default: |-
          version: v1
          flags:
            migStrategy: "none"
            failOnInitError: true
            nvidiaDriverRoot: "/"
            plugin:
              passDeviceSpecs: false
              deviceListStrategy: "envvar"
              deviceIDStrategy: "uuid"
