apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 30m
  chart:
    spec:
      chart: podinfo
      version: 6.7.0
      sourceRef:
        kind: HelmRepository
        name: podinfo
      interval: 12h
  releaseName: podinfo

  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: le-prod
      hosts:
        - host: ${podinfoIngressHost:prometheus.k8s.vincentdupain.com}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: podinfo-service-cert
          hosts:
            - ${podinfoIngressHost:prometheus.k8s.vincentdupain.com}