---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux
  prune: false
  sourceRef:
    kind: GitRepository
    name: gitops-apps
  targetNamespace: default
