---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-k8s-infra-configs
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-k8s-infra
  dependsOn:
    - name: gitops-k8s-infra-network
  